Repository wuhan2020/WebApp, pull requests merged in 2020-01, with the labels that each got.

#15 修复缺少iterable-observer的bug
  package.json
Labels: kind/bug

#37 feat: 优化了网站首页样式
  source/page/Home.tsx
Labels: enhancement

#25 Feat: Add Factory Page, add http env variables
  package.json
  source/model/Clinic.ts
  source/model/HTTPService.ts
  source/model/index.ts
  source/model/services/FactoryService.ts
  source/model/types/Factory.ts
  source/page/Clinic.tsx
  source/page/Factory.tsx
  source/page/Factory/edit.tsx
  source/page/Factory/index.tsx
  source/page/index.tsx
Labels: area/factory

#44 【优化】优化网站文字内容
  source/page/Hotel/index.tsx
  source/page/Logistics/index.tsx
Labels: enhancement

#45 添加省市区筛选
  source/model/district/Area.ts
  source/model/index.ts
  source/page/Hospital/index.tsx
Labels: kind/feature
