Repository wuhan2020/WebApp, pull requests merged in 2024-09, with the labels that each got.

#93 疫情图表性能优化
  package.json
  pnpm-lock.yaml
  source/page/Map/adapter/isaaclin.ts
  source/page/Map/component/HierarchicalVirusMap.tsx
  source/page/Map/component/VirusChart.tsx
  source/page/Map/component/VirusMap.tsx
  source/page/Map/data/province.ts
  source/page/Map/index.tsx
  source/page/data/menu.ts
  source/page/index.tsx
  source/service/Epidemic.ts
Labels: feature

#95 [add] GitHub PR badges
  .github/pr-badge.yml
  .github/workflows/image-action.yml
  .github/workflows/main.yml
  .github/workflows/push.yml
  package.json
  pnpm-lock.yaml
  source/index.tsx
  source/model/Session.ts
  source/service/AMap.ts
  tsconfig.json
Labels: enhancement

#97 [fix]Fix map json path, map data request API add range date filter condition
  pnpm-lock.yaml
  source/page/Map/component/EChartsMap.tsx
  source/page/Map/component/VirusMap.tsx
  source/page/Map/data/province.ts
  source/service/Epidemic.ts
Labels: bug
